[build]
  base = "frontend/ReportIncidents"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # Set these in Netlify UI: Site settings > Environment variables
  # VITE_API_URL = "https://your-backend-url.com/api"
  # VITE_SOCKET_URL = "https://your-backend-url.com"
  # VITE_LANDING_PAGE_URL = "https://aegis-landing.netlify.app"
